<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Mukhesh" ignored="0" name="BankingApp test" tests="7" failures="3" timestamp="11 Jul 2019 05:38:32 GMT" time="130.125" errors="0">
  <testcase name="loginTest" time="3.6" classname="com.netbanking.testCases.TC_LoginTest_001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.netbanking.testCases.TC_LoginTest_001.loginTest(TC_LoginTest_001.java:31)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="loginDDT" time="11.284" classname="com.netbanking.testCases.TC_LoginDDT_002"/>
  <testcase name="loginDDT" time="5.355" classname="com.netbanking.testCases.TC_LoginDDT_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.netbanking.testCases.TC_LoginDDT_002.loginDDT(TC_LoginDDT_002.java:30)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="10.1" classname="com.netbanking.testCases.TC_LoginDDT_002"/>
  <testcase name="loginDDT" time="5.428" classname="com.netbanking.testCases.TC_LoginDDT_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.netbanking.testCases.TC_LoginDDT_002.loginDDT(TC_LoginDDT_002.java:30)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="11.291" classname="com.netbanking.testCases.TC_LoginDDT_002"/>
  <testcase name="addNewCustomer" time="17.228" classname="com.netbanking.testCases.TC_AddCustomer_003"/>
</testsuite> <!-- BankingApp test -->
